env_params:
  env_name: "../Environments/CartPole/Environment.exe"
  frame_stacking: false
  frames_stack_size: 3
  num_envs: 2
  seed: 0
policy_params:
  clip_grads: 0.5
  clip_ratio: 0.2
  ent_coef: 0.05
  hidden_sizes:
  - 32
  - 32
  lr: 0.001
  target_kl: 0.01
  train_iters: 50
  v_coef: 0.5
train_params:
  epochs: 1000
  gamma: 0.99
  lam: 0.97
  load_model: false
  nn_architecure: "simple_actor_critic"
  num_mini_batches: 4
  save_freq: 5
  steps_per_epoch: 300
  trainer: "PPO"
  training: true
